esphome:
  name: 
  

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: NONE

# Enable Home Assistant API
api:
  encryption:
    key: 

ota:
  platform: esphome
  password: 

wifi:
  ssid: 
  password: 
  domain: 

  ap:
    ssid: "Fallback Hotspot"
    password:

captive_portal:

light:
  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    id: backlight
    restore_mode: ALWAYS_ON
  - platform: rgb
    name: LED
    id: led
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: ALWAYS_OFF

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

# Hardware related setup
spi:
  - id: tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12
  - id: touch
    clk_pin: GPIO25
    mosi_pin: GPIO32
    miso_pin: GPIO39

output:
  - platform: ledc
    pin: GPIO21
    id: backlight_pwm
  - platform: ledc
    id: output_red
    pin: GPIO4
    inverted: true
  - platform: ledc
    id: output_green
    pin: GPIO16
    inverted: true
  - platform: ledc
    id: output_blue
    pin: GPIO17
    inverted: true

# Display setup
display:
  - platform: ili9xxx
    id: my_display
    model: ili9341
    spi_id: tft
    cs_pin: GPIO15
    dc_pin: GPIO2
    transform:
      swap_xy: true
    dimensions:
      width: 320
      height: 240
    auto_clear_enabled: False
    update_interval: never
    data_rate: 40MHz
# Touchscreen setup
touchscreen:
  id: my_touch
  platform: xpt2046
  spi_id: touch
  cs_pin: GPIO33
  interrupt_pin: GPIO36
  update_interval: 50ms
  threshold: 600
  calibration:
    x_min: 180
    x_max: 3800
    y_min: 240
    y_max: 3860
  transform:
    swap_xy: true
# LVGL Setup
lvgl:
  displays:
    - my_display
  buffer_size: 0.25
  touchscreens:
    - my_touch
    # Configure Buttons
  pages:
    - id: main_page
      widgets:
        - buttonmatrix:
            bg_color: 0x000000
            border_color: 0x000000 
            outline_color: 0x000000 
            x: 0
            y: 0
            width: 320
            height: 240
            items:
              pressed:
                bg_color: 0xFFFF00
            id: matrix_id
            one_checked: true 
            rows:
              - buttons:
                - id: button_1
                  text: "ON"
                  control:
                    checkable: true
                  on_press:
                      - switch.toggle: projectorpoweron
                - id: button_2
                  text: "CAST"
                  control:
                    checkable: true
                    no_repeat: true
                  on_press:
                      - switch.toggle: projectorpoweron
                  on_release:
                      - switch.toggle: projectorhdmi1
                - id: button_3
                  text: "VOL+"
                  on_press:
                      - switch.toggle: projectorvolumeincrease
              - buttons:
                - id: button_4
                  text: "OFF"
                  control:
                    checkable: true
                  on_press:
                      - switch.toggle: projectorpoweroff
                - id: button_5
                  text: "HDMI"
                  control:
                    checkable: true
                    no_repeat: true
                  on_press:
                      - switch.toggle: projectorpoweron
                  on_release:
                      - switch.toggle: projectorhdmi2
                - id: button_6
                  text: "VOL-"
                  on_press:
                      - switch.toggle: projectorvolumedecrease



# Configure UART commands
switch:
  - platform: uart
    name: "Power ON"
    data: "PWR ON\r\n, PWR ON\r\n"
    id: projectorpoweron

  - platform: uart
    name: "Power OFF"
    data: "PWR OFF\r\n, PWR OFF\r\n"
    id: projectorpoweroff

  - platform: uart
    name: "HDMI 3"
    data: "SOURCE C0\r\n, SOURCE C0\r\n"
    id: projectorhdmi3

  - platform: uart
    name: "HDMI 1"
    data: "SOURCE 30\r\n, SOURCE 30\r\n"
    id: projectorhdmi1

  - platform: uart
    name: "HDMI 2"
    data: "SOURCE A0\r\n, SOURCE A0\r\n"
    id: projectorhdmi2

  - platform: uart
    name: "Computer1"
    data: "SOURCE 11\r\n"
    id: projectorcomputer1

  - platform: uart
    name: "Computer2"
    data: "SOURCE 21\r\n"
    id: projectorcomputer2

  - platform: uart
    name: "Volume Increase"
    data: "VOL INC\r\n"
    id: projectorvolumeincrease

  - platform: uart
    name: "Volume Decrease"
    data: "VOL Dec\r\n"
    id: projectorvolumedecrease
